# Generated by Django 3.0.3 on 2020-02-20 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookinfo',
            table='bookinfo',
        ),
        migrations.AlterModelTable(
            name='heroinfo',
            table='heroinfo',
        ),
    ]
